### ISSUE TITLE
Leaching fraction calculator - Sarah's email

### ISSUE THREAD

**Issue by skp703** [skp703/CW3#1]
-  I found 1 misspelling (noted in the screenshot attached). 

But a different question - perhaps (and I hate to ask / suggest this).  The users will be growers - not the general public: so 
-  alphabetize by botanical name rather than common name … cause that’s how the growers will likely look for them.
- Also perhaps say what you are computing - because I played with the #s a little bit - went with an EC of 3.0, moderately tolerant - so leaching fraction 0.34, with a current irrigation time of 1hours - 1.34, then if I typed in 1.34 hours, it recommend 1.79 hours … should there not be a point at which what you do and what is recommended are the same value?  (or am I just overthinking the problem)?.  Cause I could see a grower type in - 2 hours of irrigation - see that that would require 2.8 hours of irrigation, type in 2.8 hours of irrigation, and see the # go up again and get frustrated … or perhaps a bit more intro on how to use the tool, what the results will say to avoid this potential issue.

![lf](https://user-images.githubusercontent.com/5489049/48284749-93397180-e41d-11e8-8c9c-9bae066ce6ee.png)

**Comment by skp703** [comment]
Updated Taxonomy to Type
Fixed Lulium to Lolium

I think the best way to look is to search. So if I'm looking for some pine ... start typing pine see attached pic.
![image](https://user-images.githubusercontent.com/5489049/48310238-e6f4a980-e548-11e8-84a9-2d904e432288.png)

Will defer to Bruno for the later part of the question.

**Comment by brunopitton** [comment]
Let's include for irrigation time output: "Enter irrigation amount and rate or enter the irrigation time to calculate the new irrigation time that includes leaching fraction.” That should clarify the irrigation input and runtime output. 

It should be stated at the plant taxa selection (maybe in the question mark circle) that one can search for the plant they're looking for.

**Comment by brunopitton** [comment]
Loren had a couple of comments: EC of irrigation water should have limits, it cannot be negative. For sensitive plants, EC < 2, moderately sensitive EC < 3. I think that Moderately tolerant EC < 5 dS/m and and Tolerant EC < 6 but I don't have any supporting documents for these numbers. In "water to replace..."  which is a bad way of saying ET, cannot be negative, should have upper limit. In California our max daily ETo is 0.4, but could be as high as 2 in. once adjusted for ETc, so we should set the limit at 5 in. Set application rate upper limit to 4 in and cannot be negative. If someone tries to enter higher numbers because improper irrigation/ET calculations, the output should say, "Values entered are improbably. Use the runtime tab."

**Comment by brunopitton** [comment]
Leaching Fraction description
Leaching fraction is the ratio of the volume of water that drains out of the bottom of the container to total amount of applied irrigation water. Using irrigation water with salts present, fertilizer and undesirable salts, results in salt accumulation in the growing substrate because plants can exclude salts when taking up water. To avoid negative effects on plant growth and quality, these salts need to be removed from either the irrigation water or the root zone. Salts can be removed from irrigation water with reverse osmosis, but this is expensive, especially for large volumes of water. An alternative is to irrigate with enough water to leach salts from the growing media. Recycled water typically has higher salts than source water, so reducing salt accumulation in the root zone is especially important for growers recycling irrigation runoff water. This tool will help determine the correct leaching fraction based on plant salt sensitivity and salt concentration in irrigation water. For more information, refer to the resources at the bottom of the page.

Include at bottom of page:
"Principle from:
Evans, R.Y., Dodge, L.L. and Newman, J. (2007) Nutrient Management in Nursery and Floriculture, p. 9, UC ANR."

"Plant salinity tolerance data from:
Kratsch, H., Olsen, S., Rupp, L., Cardon, G. and Heflebower, R. (2008) Soil Salinity and Ornamental Plant Selection, Utah State University Cooperative Extension.
Miyamoto, S. (2008) Salt tolerance of landscape plants common to the southwest, Texas Water Resources Institute."

**Comment by brunopitton** [comment]
[LF tool_latin.xlsx](https://github.com/skp703/CW3/files/3387796/LF.tool_latin.xlsx)

**Comment by brunopitton** [comment]
[LF_cleanwater3.pptx](https://github.com/skp703/CW3/files/3394565/LF_cleanwater3.pptx)

**Comment by skp703** [comment]
Done all... and added a citation. Bruno who should be authors?

**Comment by skp703** [comment]
Not adding ppt and excel for consistency at this time.

**Comment by brunopitton** [comment]
Here are the proposed authors.
Pitton, B.J.L., L.R. Oki, J.C Majsztrik, S. Kumar. 2018. Leaching Fraction Calculator. 

Saurav, to clarify, you will be updating the tool with the botanical names first (excel sheet)?

**Comment by brunopitton** [comment]
I made a couple of changes to the description paragraph. See below.
Thanks

Leaching fraction is the ratio of the volume of water that drains out of the bottom of the container to total amount of applied irrigation water. Irrigating with water containing salts, such as fertilizer or undesirable salts, causes salt accumulation in the growing media. To avoid negative effects on plant growth and quality, these salts need to be removed from either the irrigation water or the root zone. Salts can be removed from irrigation water with reverse osmosis, but this is expensive, especially for large volumes of water. An alternative is to irrigate with enough water to leach salts from the growing media. Recycled water typically has higher salt concentration than source water, making the reduction of salt accumulation in the root zone especially important for growers who are recycling irrigation runoff water. This tool will help determine the correct leaching fraction based on plant salt sensitivity and salt concentration in irrigation water. For more information, refer to the resources at the bottom of the page.

**Comment by skp703** [comment]
Not changing the name order. We have discussed this several times. I though common name first is what we are going for.

**Comment by brunopitton** [comment]
We did discuss the naming and the consensus is to put botanical name first. Loren, Sarah, John M. all recommended it and I agree. I was confused on the conference call because I thought it had already been changed to botanical name first. Thanks for finishing these up

**Comment by skp703** [comment]
okay done.
