### ISSUE TITLE
SSF sizing tool

### ISSUE THREAD

**Issue by jenniferparke** [skp703/CW3#2]
I don't see anything regarding a minimum depth for the SSF. Isn't there one?

**Comment by skp703** [comment]
Not in the tool. I think we are just computing surface area based on flow rate and volume treated.  Are you aware of any guidelines? We may just put that on the tool for reference.

**Comment by jenniferparke** [comment]
Hi Saurav,
It would be good to get Loren Oki’s input here, as he is the expert. I know that the microbial crust at the surface does account for some of the required depth; as this is often physically removed to restore the SSF effectiveness.

Jennifer

Jennifer L. Parke
Professor, Senior Research
Dept. of Crop and Soil Science & Dept. of Botany and Plant Pathology
3017 Ag and Life Sciences Building
Oregon State University
Corvallis, OR 97331 USA
Phone 541-737-8170
Email Jennifer.Parke@oregonstate.edu

**Comment by brunopitton** [comment]
There is a minimum depth, I don't know exactly off the top of my head but the sand bed can be pretty shallow. The recommendation is to start with 3 feet of sand and as you clean the surface over time, a little sand (~1") is removed each time. This allows for a lot of cleaning if needed but should last a long time if prefiltering particulates. Eventually, the sand bed will be so shallow that it should be replaced.  Loren did edit my original excel sheet this is based on.

The original intent is to help growers calculate surface area based on volume of water they want to treat in a day. Sorry I didn't answer sooner.

**Comment by brunopitton** [comment]
Tool description: 
"Slow sand filters (SSF) are biological treatment systems that can remove plant pathogens including water molds, viruses, fungi, and bacteria. SSFs can be confused with rapid sand filters because both technologies use sand as a substrate. Rapid sand filters utilize very coarse sand grains (>1 mm) and operate at high flow rates (2 to 20 gpm per square foot of sand bed) to remove particulates from irrigation water. In comparison, SSFs use medium sand grains (<0.6 mm) with very slow flow rates (0.06 to 0.2 gpm per square foot) to remove pathogens. For more information, read the trade article attached below.
This tool will help determine the SSF surface area for a given flow rate and daily volume of water to be treated."

[Am nurseryman SSF 4 pg.pdf](https://github.com/skp703/CW3/files/3384068/Am.nurseryman.SSF.4.pg.pdf)

**Comment by skp703** [comment]
done.. Do we need the pdf in Spanish?

**Comment by brunopitton** [comment]
Proposed authors
Pitton, B.J.L., L.R. Oki, J.C Majsztrik, S. Kumar.

**Comment by brunopitton** [comment]
> 
> 
> done.. Do we need the pdf in Spanish?

It would probably help but I am incapable of translating it. Not sure if anyone else has time.

**Comment by brunopitton** [comment]
Can you please change the pdf from "more details" to "supplemental article"? Thanks

**Comment by brunopitton** [comment]
Loren's comments
"On the SSF sizing tool, the recommended flow rate range shows up as percent signs and not numeric values.  The minimum flow rate should be 1.2 gph/ft^2 and the mx is 2.2 gph/ft^2.

 

I also think that the word “tank” should not be used and “filter” is more appropriate. 

 

Loren"

**Comment by skp703** [comment]
Used John's language on "more detail". Changed to "slow sand filter article". Serves a similar purpose. The %sign issue is fixed.
